

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main/MainHeader";
import Footer from "@/components/main/footer/Footer";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/components/util/http";
import StoreProvider from "./StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Audiophile Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <QueryClientProvider client={queryClient}>
            <MainHeader />
            {children}
            <Footer />
          </QueryClientProvider>
          </StoreProvider>       
      </body>
    </html>
  );
}
